name: Archivist
main: org.crayne.archivist.ArchivistPlugin
version: 1.0
api-version: 1.20
description: Core plugin for anarchived

commands:
  goto:
    description: Teleports a player to any specific save and variant
  go:
    description: GUI-based base/server search to quickly find a save
  reindex:
    description: Reindexes the entire archive automatically